sonar.projectKey=axion-telemetry-query-service
sonar.projectName=Axion Telemetry Query Service
sonar.organization=devopsinsiders
sonar.sources=.
sonar.python.version=3.12
sonar.exclusions=**/test/**,**/tests/**,**/*_test.py