apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: axion-postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: axion
  source:
    repoURL: https://github.com/santandevops01012025/Axion-UI.git
    path: gitops/db
    targetRevision: main
    helm:
      parameters:
        - name: schemaImage.repository
          value: ghcr.io/devopsinsiders/axion-database-schema
  destination:
    server: https://kubernetes.default.svc
    namespace: axion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true