sonar.projectKey=axion-data-simulator
sonar.projectName=Axion Data Simulator
sonar.organization=devopsinsiders
sonar.sources=.
sonar.python.version=3.12
sonar.exclusions=**/test/**,**/tests/**,**/*_test.py