apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: axion
  labels:
    app.kubernetes.io/name: axion-postgres
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: axion-postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      protocol: TCP
      name: postgres