sonar.projectKey=axion-ingestion-service
sonar.projectName=Axion Ingestion Service
sonar.organization=devopsinsiders
sonar.sources=.
sonar.python.version=3.12
sonar.exclusions=**/test/**,**/tests/**,**/*_test.py