replicaCount: 1

image:
  repository: ghcr.io/santandevops01012025/axion-ingestion-service
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

dbSecret:
  name: axion-db-credentials
  key: DATABASE_URL

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: false

podAnnotations: {}
imagePullSecrets: []
nodeSelector: {}
tolerations: []
affinity: {}